### ISSUE TITLE
mcrypt 可以 openssl 不能用 

### ISSUE THREAD

**Issue by slife88** [killworm737/QrcodeInvoice#3]
你好，原本用的 mcrypt 上財政部檢查條碼是正確的，用openssl 編出來的檢查會失敗，兩個方法編出來的結果也不同，不知道是什麼原因，如何處理？謝謝。

**Comment by killworm737** [comment]
請問你的環境設定是甚麼?我用php 5.4 與 php 7.1 跑兩種function，跑出來的結果都是相同的，或者你給我你測試的範例參數，我跑出來試試看

**Comment by slife88** [comment]
你好，OK了，程式沒問題，是我有些地方弄錯了。很有幫助，謝謝你。
